# Gremlin Helm chart values
# Using certificate-based authentication

gremlin:
  teamID: "438c58ec-03db-47ac-8c58-ec03db67ac42"
  clusterID: "istio-otel-demo-cluster"
  
  # Certificate-based authentication
  certSecret:
    create: true
    teamCertificate: |
      -----BEGIN CERTIFICATE-----
      MIIB7TCCAZSgAwIBAgIBATAKBggqhkjOPQQDAjBxMSMwIQYDVQQDDBpHcmVtbGlu
      IENsaWVudCBDZXJ0aWZpY2F0ZTElMCMGA1UECwwcR3JlbWxpbiBTb2x1dGlvbnMg
      QXJjaGl0ZWN0czEjMCEGA1UECgwaRmlnQ2xvcHNFbnRlcnByaXNlcyAtIFNlYW4w
      HhcNMjUwMzMxMTgyOTE1WhcNMjYwMzMxMTgyOTE1WjBxMSMwIQYDVQQDDBpHcmVt
      bGluIENsaWVudCBDZXJ0aWZpY2F0ZTElMCMGA1UECwwcR3JlbWxpbiBTb2x1dGlv
      bnMgQXJjaGl0ZWN0czEjMCEGA1UECgwaRmlnQ2xvcHNFbnRlcnByaXNlcyAtIFNl
      YW4wWTATBgcqhkjOPQIBBggqhkjOPQMBBwNCAAQTk7S9HRgXCQcTnhLlHeyJG+Jt
      IoDTnSd92Gz9vVsx5+Zh+Tl6Qni0ct6g84reuEzv9tYNws82onpvdyJd41KAox0w
      GzAJBgNVHRMEAjAAMA4GA1UdDwEB/wQEAwIHgDAKBggqhkjOPQQDAgNHADBEAiAi
      iG3gU+gmihrNfIMVsdV41CxhgD0Bca9VP3qUbcKcSQIgIfAoUIYc/UXIVwrifz0m
      uPUaQ08zctqzMZlFCNsHJ6I=
      -----END CERTIFICATE-----
    teamPrivateKey: |
      -----BEGIN EC PRIVATE KEY-----
      MHcCAQEEIGs2Vo2eIIZXpdgju5lV9FyoHa7b6Wzf4gO1hfwCGkzBoAoGCCqGSM49
      AwEHoUQDQgAEE5O0vR0YFwkHE54S5R3siRvibSKA050nfdhs/b1bMefmYfk5ekJ4
      tHLeoPOK3rhM7/bWDcLPNqJ6b3ciXeNSgA==
      -----END EC PRIVATE KEY-----

# Enable Istio integration
istio:
  enabled: true
  namespace: istio-system

# Run Gremlin agent in daemonset mode
disableDetachedAgents: true

# Required host access
hostPID: true
hostNetwork: true
hostIPC: true

dnsPolicy: ClusterFirstWithHostNet

# Required security context for Gremlin agent
securityContext:
  privileged: true
  capabilities:
    add: ["NET_ADMIN", "SYS_ADMIN", "SYS_PTRACE", "KILL", "NET_BROADCAST"]

# Required volumes for Gremlin agent
volumes:
  - name: host-mount
    hostPath:
      path: /
  - name: dev
    hostPath:
      path: /dev
  - name: run
    hostPath:
      path: /run
  - name: sys
    hostPath:
      path: /sys
  - name: var-run
    hostPath:
      path: /var/run
  - name: docker-sock
    hostPath:
      path: /var/run/docker.sock
  - name: os-release
    hostPath:
      path: /etc/os-release
  - name: etc-os-release
    hostPath:
      path: /usr/lib/os-release
  - name: cgroup
    hostPath:
      path: /sys/fs/cgroup

# Enable service mesh integration
xds:
  enabled: true
  port: 50051

# Resource requests and limits
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi
