spec:
  template:
    spec:
      containers:
      - name: load-generator
        volumeMounts:
        - name: config
          mountPath: /usr/src/app/locustfile.py
          subPath: locustfile.py
      volumes:
      - name: config
        configMap:
          name: load-generator-config
          items:
          - key: locustfile.py
            path: locustfile.py
