#!/bin/bash
#
# Terraform wrapper for fictional-computing-machine integration
# References Terraform modules directly from GitHub
#

# Source common functions if not already loaded
if [[ -z "$RED" ]]; then
    LIB_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    source "$LIB_DIR/common.sh"
fi

# Configuration
FCM_REPO="git@github.com:gremlin/fictional-computing-machine.git"
FCM_MODULE_PATH="terraform/modules/sa_demo"
FCM_VERSION="${FCM_VERSION:-main}"  # Can override with env var or --fcm-version flag
TERRAFORM_WORK_DIR="${SCRIPT_DIR}/../terraform/workspace"

# Get AWS account ID
get_aws_account_id() {
    aws sts get-caller-identity --query Account --output text 2>/dev/null
}

# Create Terraform workspace for deployment
terraform_create_workspace() {
    local subdomain="$1"
    local owner="$2"
    local enable_eks="$3"
    local enable_ecs="$4"
    local team_id_arn="$5"
    local cert_arn="$6"
    local key_arn="$7"
    
    local workspace_dir="$TERRAFORM_WORK_DIR/$subdomain"
    local aws_account=$(get_aws_account_id)
    
    log_info "Creating Terraform workspace for: $subdomain"
    log_info "Using fictional-computing-machine version: $FCM_VERSION"
    
    mkdir -p "$workspace_dir"
    
    # Create main.tf - Single module reference
    cat > "$workspace_dir/main.tf" <<EOF
# Generated by workshop.sh
# References fictional-computing-machine modules from GitHub
# Version: ${FCM_VERSION}

module "demo" {
  source = "${FCM_REPO}//${FCM_MODULE_PATH}?ref=${FCM_VERSION}"
  
  subdomain = var.subdomain
  owner = var.owner
  enable_eks = var.enable_eks
  enable_ecs_fargate = var.enable_ecs_fargate
  
  gremlin_team_id_arn = var.gremlin_team_id_arn
  gremlin_team_certificate_arn = var.gremlin_team_certificate_arn
  gremlin_team_private_key_arn = var.gremlin_team_private_key_arn
}

# Outputs for workshop scripts
output "cluster_name" {
  description = "EKS cluster name"
  value       = module.demo.cluster_name
}

output "cluster_endpoint" {
  description = "EKS cluster endpoint"
  value       = module.demo.cluster_endpoint
}

output "cluster_region" {
  description = "AWS region"
  value       = module.demo.cluster_region
}

output "alb_dns_name" {
  description = "ALB DNS name"
  value       = module.demo.alb_dns_name
}

output "demo_frontend_url" {
  description = "OpenTelemetry Demo frontend URL"
  value       = module.demo.demo_frontend_url
}

output "monitoring_url" {
  description = "Monitoring platform URL"
  value       = module.demo.monitoring_url
}

output "otel_demo_target_group_arn" {
  description = "Target group ARN for OpenTelemetry Demo"
  value       = module.demo.otel_demo_target_group_arn
}

output "monitoring_target_group_arn" {
  description = "Target group ARN for monitoring"
  value       = module.demo.monitoring_target_group_arn
}

output "gremlin_team_id_arn" {
  description = "ARN of Gremlin Team ID secret"
  value       = module.demo.gremlin_team_id_arn
  sensitive   = true
}

output "gremlin_team_certificate_arn" {
  description = "ARN of Gremlin Team Certificate secret"
  value       = module.demo.gremlin_team_certificate_arn
  sensitive   = true
}

output "gremlin_team_private_key_arn" {
  description = "ARN of Gremlin Team Private Key secret"
  value       = module.demo.gremlin_team_private_key_arn
  sensitive   = true
}

output "subdomain" {
  description = "Subdomain used for this deployment"
  value       = module.demo.subdomain
}

output "owner" {
  description = "Owner of this deployment"
  value       = module.demo.owner
}
EOF
    
    # Create variables.tf
    cat > "$workspace_dir/variables.tf" <<EOF
variable "subdomain" {
  description = "Unique subdomain for this deployment"
  type        = string
  default     = "$subdomain"
}

variable "owner" {
  description = "Owner of this deployment"
  type        = string
  default     = "$owner"
}

variable "enable_eks" {
  description = "Enable EKS cluster"
  type        = bool
  default     = $enable_eks
}

variable "enable_ecs_fargate" {
  description = "Enable ECS Fargate cluster"
  type        = bool
  default     = $enable_ecs
}

variable "gremlin_team_id_arn" {
  description = "ARN of Gremlin Team ID secret in AWS Secrets Manager"
  type        = string
  default     = "$team_id_arn"
}

variable "gremlin_team_certificate_arn" {
  description = "ARN of Gremlin Team Certificate secret in AWS Secrets Manager"
  type        = string
  default     = "$cert_arn"
}

variable "gremlin_team_private_key_arn" {
  description = "ARN of Gremlin Team Private Key secret in AWS Secrets Manager"
  type        = string
  default     = "$key_arn"
}
EOF
    
    # Create terraform.tf (backend config)
    cat > "$workspace_dir/terraform.tf" <<EOF
terraform {
  required_version = ">= 1.13"
  
  backend "s3" {
    bucket         = "gremlin-terraform-state-us-east-2"
    key            = "workshop/${subdomain}/terraform.tfstate"
    region         = "us-east-2"
    encrypt        = true
    dynamodb_table = "gremlin-terraform-locks"
  }
}

provider "aws" {
  region              = "us-east-2"
  allowed_account_ids = ["${aws_account}"]
}
EOF
    
    log_success "Terraform workspace created: $workspace_dir"
}

# Initialize Terraform
terraform_init() {
    local workspace_dir="$1"
    
    log_info "Initializing Terraform in $workspace_dir"
    
    cd "$workspace_dir" || return 1
    terraform init -upgrade
}

# Plan Terraform changes
terraform_plan() {
    local workspace_dir="$1"
    
    log_info "Planning Terraform changes"
    
    cd "$workspace_dir" || return 1
    terraform plan -out=tfplan
}

# Apply Terraform configuration
terraform_apply() {
    local workspace_dir="$1"
    
    log_info "Applying Terraform configuration"
    
    cd "$workspace_dir" || return 1
    
    if [[ -f "tfplan" ]]; then
        terraform apply tfplan
    else
        log_warning "No plan file found, running apply without plan"
        terraform apply -auto-approve
    fi
}

# Destroy Terraform-managed infrastructure
terraform_destroy() {
    local workspace_dir="$1"
    
    log_info "Destroying Terraform-managed infrastructure"
    
    cd "$workspace_dir" || return 1
    terraform destroy -auto-approve
}

# Get single Terraform output
terraform_output() {
    local workspace_dir="$1"
    local output_name="$2"
    
    cd "$workspace_dir" || return 1
    terraform output -raw "$output_name" 2>/dev/null
}

# Get all Terraform outputs as JSON
terraform_output_json() {
    local workspace_dir="$1"
    
    cd "$workspace_dir" || return 1
    terraform output -json
}

# Export Terraform outputs to environment variables
export_terraform_outputs() {
    local workspace_dir="$1"
    local outputs_json
    
    log_info "Exporting Terraform outputs to environment"
    
    outputs_json=$(terraform_output_json "$workspace_dir")
    
    if [[ -z "$outputs_json" ]]; then
        log_error "Failed to retrieve Terraform outputs"
        return 1
    fi
    
    export CLUSTER_NAME=$(echo "$outputs_json" | jq -r '.cluster_name.value // empty')
    export CLUSTER_ENDPOINT=$(echo "$outputs_json" | jq -r '.cluster_endpoint.value // empty')
    export CLUSTER_REGION=$(echo "$outputs_json" | jq -r '.cluster_region.value // empty')
    export ALB_DNS_NAME=$(echo "$outputs_json" | jq -r '.alb_dns_name.value // empty')
    export DEMO_FRONTEND_URL=$(echo "$outputs_json" | jq -r '.demo_frontend_url.value // empty')
    export MONITORING_URL=$(echo "$outputs_json" | jq -r '.monitoring_url.value // empty')
    export OTEL_DEMO_TARGET_GROUP_ARN=$(echo "$outputs_json" | jq -r '.otel_demo_target_group_arn.value // empty')
    export MONITORING_TARGET_GROUP_ARN=$(echo "$outputs_json" | jq -r '.monitoring_target_group_arn.value // empty')
    export GREMLIN_TEAM_ID_ARN=$(echo "$outputs_json" | jq -r '.gremlin_team_id_arn.value // empty')
    export GREMLIN_TEAM_CERTIFICATE_ARN=$(echo "$outputs_json" | jq -r '.gremlin_team_certificate_arn.value // empty')
    export GREMLIN_TEAM_PRIVATE_KEY_ARN=$(echo "$outputs_json" | jq -r '.gremlin_team_private_key_arn.value // empty')
    export SUBDOMAIN=$(echo "$outputs_json" | jq -r '.subdomain.value // empty')
    export OWNER=$(echo "$outputs_json" | jq -r '.owner.value // empty')
    
    # Set AWS_REGION if not already set
    export AWS_REGION="${CLUSTER_REGION:-us-east-2}"
    
    log_success "Terraform outputs exported"
    log_info "Cluster: $CLUSTER_NAME"
    log_info "Region: $AWS_REGION"
    log_info "Frontend URL: $DEMO_FRONTEND_URL"
    log_info "Monitoring URL: $MONITORING_URL"
}

# Fetch Gremlin credentials from AWS Secrets Manager
fetch_gremlin_credentials() {
    local region="${AWS_REGION:-us-east-2}"
    
    log_info "Fetching Gremlin credentials from AWS Secrets Manager"
    
    if [[ -z "$GREMLIN_TEAM_ID_ARN" ]]; then
        log_error "GREMLIN_TEAM_ID_ARN not set"
        return 1
    fi
    
    export GREMLIN_TEAM_ID=$(aws secretsmanager get-secret-value \
        --secret-id "$GREMLIN_TEAM_ID_ARN" \
        --region "$region" \
        --query 'SecretString' \
        --output text 2>/dev/null)
    
    if [[ -z "$GREMLIN_TEAM_ID" ]]; then
        log_error "Failed to fetch Gremlin Team ID from Secrets Manager"
        return 1
    fi
    
    export GREMLIN_TEAM_CERTIFICATE=$(aws secretsmanager get-secret-value \
        --secret-id "$GREMLIN_TEAM_CERTIFICATE_ARN" \
        --region "$region" \
        --query 'SecretString' \
        --output text 2>/dev/null)
    
    if [[ -z "$GREMLIN_TEAM_CERTIFICATE" ]]; then
        log_error "Failed to fetch Gremlin Team Certificate from Secrets Manager"
        return 1
    fi
    
    export GREMLIN_TEAM_PRIVATE_KEY=$(aws secretsmanager get-secret-value \
        --secret-id "$GREMLIN_TEAM_PRIVATE_KEY_ARN" \
        --region "$region" \
        --query 'SecretString' \
        --output text 2>/dev/null)
    
    if [[ -z "$GREMLIN_TEAM_PRIVATE_KEY" ]]; then
        log_error "Failed to fetch Gremlin Team Private Key from Secrets Manager"
        return 1
    fi
    
    # Also fetch API key if available (for PNI)
    if [[ -n "${GREMLIN_API_KEY_ARN:-}" ]]; then
        export GREMLIN_API_KEY=$(aws secretsmanager get-secret-value \
            --secret-id "$GREMLIN_API_KEY_ARN" \
            --region "$region" \
            --query 'SecretString' \
            --output text 2>/dev/null)
    fi
    
    log_success "Gremlin credentials fetched from Secrets Manager"
    log_info "Team ID: ${GREMLIN_TEAM_ID:0:8}..."
}

# Resolve Gremlin credentials from owner name
resolve_gremlin_credentials_from_owner() {
    local owner="$1"
    local region="${AWS_REGION:-us-east-2}"
    local account=$(get_aws_account_id)
    
    log_info "Attempting to resolve Gremlin credentials for owner: $owner"
    
    # Construct ARNs based on owner
    export GREMLIN_TEAM_ID_ARN="arn:aws:secretsmanager:${region}:${account}:secret:${owner}/gremlin_team_id"
    export GREMLIN_TEAM_CERTIFICATE_ARN="arn:aws:secretsmanager:${region}:${account}:secret:${owner}/gremlin_team_certificate"
    export GREMLIN_TEAM_PRIVATE_KEY_ARN="arn:aws:secretsmanager:${region}:${account}:secret:${owner}/gremlin_team_private_key"
    
    # Check if secrets exist
    if ! aws secretsmanager describe-secret --secret-id "$GREMLIN_TEAM_ID_ARN" --region "$region" &>/dev/null; then
        log_warning "Secrets not found for owner: $owner"
        log_info "Expected secrets:"
        echo "  - ${owner}/gremlin_team_id"
        echo "  - ${owner}/gremlin_team_certificate"
        echo "  - ${owner}/gremlin_team_private_key"
        return 1
    fi
    
    log_success "Found Gremlin secrets for owner: $owner"
    
    # Fetch credentials
    fetch_gremlin_credentials
}

# Validate Terraform configuration
terraform_validate() {
    local workspace_dir="$1"
    
    log_info "Validating Terraform configuration"
    
    cd "$workspace_dir" || return 1
    terraform validate
}

# Get workspace directory for subdomain
get_workspace_dir() {
    local subdomain="$1"
    echo "$TERRAFORM_WORK_DIR/$subdomain"
}

# Check if workspace exists
workspace_exists() {
    local subdomain="$1"
    local workspace_dir=$(get_workspace_dir "$subdomain")
    
    [[ -d "$workspace_dir" ]] && [[ -f "$workspace_dir/main.tf" ]]
}
