apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-demo-collector
  namespace: monitoring
  labels:
    release: prometheus
    app.kubernetes.io/name: otel-demo
spec:
  namespaceSelector:
    matchNames:
      - otel-demo
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
  endpoints:
    - port: prom-metrics
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-demo-prometheus
  namespace: monitoring
  labels:
    release: prometheus
    app.kubernetes.io/name: otel-demo
spec:
  namespaceSelector:
    matchNames:
      - otel-demo
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-demo-grafana
  namespace: monitoring
  labels:
    release: prometheus
    app.kubernetes.io/name: otel-demo
spec:
  namespaceSelector:
    matchNames:
      - otel-demo
  selector:
    matchLabels:
      app.kubernetes.io/name: grafana
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
