clusterName: {{ .ClusterName }}
region: {{ .Region }}
vpcId: {{ .VpcId }}
serviceAccount:
  create: false
  name: aws-load-balancer-controller
image:
  repository: 602401143452.dkr.ecr.us-east-2.amazonaws.com/amazon/aws-load-balancer-controller
  tag: v2.4.2
  pullPolicy: IfNotPresent
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi
rbac:
  create: true
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: {{ .RoleArn }}
podSecurityContext:
  fsGroup: 65534
securityContext:
  runAsNonRoot: true
  runAsUser: 65534
  readOnlyRootFilesystem: true
  allowPrivilegeEscalation: false
  capabilities:
    drop:
      - ALL
  seccompProfile:
    type: RuntimeDefault
nodeSelector:
  kubernetes.io/os: linux
tolerations:
  - key: "CriticalAddonsOnly"
    operator: "Exists"
affinity:
  nodeAffinity:
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
        - matchExpressions:
            - key: kubernetes.io/os
              operator: In
              values:
                - linux
