apiVersion: apps/v1
kind: Deployment
metadata:
  name: otel-demo-cartservice
  namespace: otel-demo
  labels:
    app.kubernetes.io/component: cartservice
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/name: otel-demo-cartservice
    app.kubernetes.io/version: 1.12.0
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: cartservice
      app.kubernetes.io/instance: otel-demo
  template:
    metadata:
      labels:
        app.kubernetes.io/component: cartservice
        app.kubernetes.io/instance: otel-demo
        app.kubernetes.io/name: otel-demo-cartservice
        app.kubernetes.io/version: 1.12.0
    spec:
      serviceAccountName: default
      containers:
      - name: cartservice
        image: ghcr.io/open-telemetry/demo:1.12.0-cartservice
        imagePullPolicy: IfNotPresent
        ports:
        - name: service
          containerPort: 8080
        env:
        - name: OTEL_SERVICE_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.labels['app.kubernetes.io/component']
        - name: OTEL_COLLECTOR_NAME
          value: otel-demo-otelcol
        - name: OTEL_EXPORTER_OTLP_METRICS_TEMPORALITY_PREFERENCE
          value: cumulative
        - name: CART_SERVICE_PORT
          value: "8080"
        - name: ASPNETCORE_URLS
          value: http://*:$(CART_SERVICE_PORT)
        - name: VALKEY_ADDR
          value: otel-demo-valkey:6379
        - name: FLAGD_HOST
          value: otel-demo-flagd
        - name: FLAGD_PORT
          value: "8013"
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://$(OTEL_COLLECTOR_NAME):4317
        - name: OTEL_RESOURCE_ATTRIBUTES
          value: service.name=$(OTEL_SERVICE_NAME),service.namespace=opentelemetry-demo,service.version=1.12.0
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 20
          periodSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
          failureThreshold: 3
        startupProbe:
          tcpSocket:
            port: 8080
          failureThreshold: 30
          periodSeconds: 10
