apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: gremlin-cpu-recording-rules
  namespace: monitoring
  labels:
    app: kube-prometheus-stack
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/part-of: kube-prometheus-stack
    release: prometheus-operator
spec:
  groups:
  - name: gremlin.cpu.rules
    rules:
    - record: gremlin:container_cpu_usage:rate5m
      expr: sum by(pod) (rate(container_cpu_usage_seconds_total[5m]))
