apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-tracing
  namespace: istio-system
spec:
  tracing:
  - providers:
    - name: otel
    randomSamplingPercentage: 100.0
    customTags:
      "k8s.namespace.name":
        literal:
          value: "%HOSTNAME%"
      "k8s.pod.name":
        literal:
          value: "%HOST%"
      "k8s.container.name":
        literal:
          value: "%CONTAINER_NAME%"
---
apiVersion: telemetry.istio.io/v1alpha1
kind: Telemetry
metadata:
  name: otel-tracing
  namespace: otel-demo
spec:
  tracing:
  - providers:
    - name: otel
    randomSamplingPercentage: 100.0
    customTags:
      "k8s.namespace.name":
        literal:
          value: "%HOSTNAME%"
      "k8s.pod.name":
        literal:
          value: "%HOST%"
      "k8s.container.name":
        literal:
          value: "%CONTAINER_NAME%"
