apiVersion: v1
kind: Service
metadata:
  name: prometheus-operator-grafana
  namespace: monitoring
spec:
  type: LoadBalancer
  ports:
    - name: http-web
      port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app.kubernetes.io/instance: prometheus-operator
    app.kubernetes.io/name: grafana
