apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: otel-collector
  namespace: monitoring
  labels:
    app.kubernetes.io/component: opentelemetry-collector
    release: prometheus-operator
spec:
  endpoints:
  - interval: 30s
    path: /metrics
    port: prometheus-metrics
  namespaceSelector:
    matchNames:
    - otel-demo
  selector:
    matchLabels:
      app.kubernetes.io/name: opentelemetry-collector
      app.kubernetes.io/instance: otel-demo
