{
 "title": "Gremlin Memory Dashboard",
 "tags": [
  "memory",
  "metrics",
  "monitoring"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "Container Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gremlin:container_memory_usage:bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Node Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes - node_memory_MemAvailable_bytes",
     "legendFormat": "Used Memory"
    },
    { "expr": "node_memory_MemAvailable_bytes", "legendFormat": "Available Memory" }
   ]
  },
  {
   "title": "Container Working Set Memory",
   "type": "timeseries",
   "gridPos": { "h": 21, "w": 24, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gremlin:container_memory_working_set:bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Container Cache Memory",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "gremlin:container_memory_cache:bytes",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}