apiVersion: v1
kind: Service
metadata:
  name: otel-demo-frontend
  namespace: otel-demo
  labels:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: otel-demo
    app.kubernetes.io/name: otel-demo-frontend
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app.kubernetes.io/component: frontend
    app.kubernetes.io/instance: otel-demo
