---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: otel-bootcamp-group-{{.TEAM_NUMBER}}
  region: us-east-2
  version: "1.28"
  tags:
    owner: {{.OWNER}}
    expiration: {{.EXPIRATION}}

managedNodeGroups:
  - name: otel-bootcamp-group-ng-{{.TEAM_NUMBER}}
    minSize: 6
    maxSize: 8
    desiredCapacity: 6
    volumeSize: 20
    instanceTypes:
      - t3.medium
      - t3a.medium
      - t2.medium
    spot: true
    iam:
      instanceRoleARN: arn:aws:iam::856940208208:role/DemosVPC-EksNodeInstanceRole
    securityGroups:
      attachIDs:
        - sg-0a499ed85cbdf45c5

vpc:
  id: vpc-0ae237bb717910ccc
  subnets:
    private:
      us-east-2a:
        id: subnet-0403fbdc0a75620d6
      us-east-2b:
        id: subnet-0dcb40d6b8fad2c03
      us-east-2c:
        id: subnet-0d36418b808d97976
    public:
      us-east-2a:
        id: subnet-08038efe886c31791
      us-east-2b:
        id: subnet-0135b61262e48f4d6
      us-east-2c:
        id: subnet-0fe7be30ec2528c4c

iam:
  serviceRoleARN: arn:aws:iam::856940208208:role/DemosVPC-EksServiceRole
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: digitalocean-dns
        namespace: default
      attachPolicyARNs:
        - arn:aws:iam::aws:policy/AmazonSSMReadOnlyAccess

# Create user accounts in new EKS cluster. By default, only the user that created the cluster
# has access. This will ensure that the entire SA/PS team has access to each cluster.
iamIdentityMappings:
  - arn: arn:aws:iam::856940208208:user/sam.whyte
    username: sam.whyte
    groups:
      - system:masters
  - arn: arn:aws:iam::856940208208:user/jessykah.bird
    username: jessykah.bird
    groups:
      - system:masters
  - arn: arn:aws:iam::856940208208:user/don
    username: don.darwin
    groups:
      - system:masters
  - arn: arn:aws:iam::856940208208:user/dan.muret@gremlin.com
    username: dan.muret
    groups:
      - system:masters
  - arn: arn:aws:iam::856940208208:user/jason.heller
    username: jason.heller
    groups:
      - system:masters